import CryptoKit
import Foundation

/// Offline validation of activation codes. Pure static, no network access.
nonisolated enum LicenseValidator {
    private static let payloadVersion = 1

    /// Production Ed25519 public key (base64, 32 bytes). The matching private key lives
    /// only on the issuing machine (`~/.light-stats-license/private.key`, generated by
    /// `script/license-tool`) and is never committed. Without it nobody can forge a code,
    /// even with full source access.
    private static let appPublicKeyBase64 = "NAImyOP6HGkW8fhRJq9zf9+tlEQ3HJ6/C6mYmEBS7qg="

    /// Validates a code against the embedded production key.
    static func validateAppCode(_ code: String) -> LicensePayload? {
        guard let keyData = Data(base64Encoded: appPublicKeyBase64),
              let key = try? Curve25519.Signing.PublicKey(rawRepresentation: keyData) else { return nil }
        return validate(code: code, publicKey: key)
    }

    /// Validates a code against an explicit key (tests inject their own keypair).
    static func validate(code: String, publicKey: Curve25519.Signing.PublicKey) -> LicensePayload? {
        guard let (payload, signature) = LicenseCodec.decode(code),
              publicKey.isValidSignature(signature, for: payload) else { return nil }
        return decodePayload(payload)
    }

    private struct PayloadJSON: Codable {
        let version: Int
        let features: [String]
        let owner: String
        let issuedAt: Int64

        private enum CodingKeys: String, CodingKey {
            case version = "v"
            case features = "f"
            case owner = "o"
            case issuedAt = "i"
        }
    }

    private static func decodePayload(_ data: Data) -> LicensePayload? {
        guard let json = try? JSONDecoder().decode(PayloadJSON.self, from: data),
              json.version == payloadVersion else { return nil }
        let features = Set(json.features.compactMap(LicensePayload.Feature.init(rawValue:)))
        return LicensePayload(
            features: features,
            owner: json.owner,
            issuedAt: Date(timeIntervalSince1970: TimeInterval(json.issuedAt))
        )
    }
}
